version: "3.8"
services:
  app:
    build: .
    ports:
      - "3005:3001"
    volumes:
      - ./public/uploads:/app/public/uploads
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./public/uploads:/usr/share/nginx/html/uploads:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 